### PR TITLE
Adds basic OmniFaces support

### PR DESCRIPTION
**Pull request by rmpestano**
- Makes OmniFaces bootstraping work 
- Tested CombinedResourceHandler and Messages utility

### CODE REVIEW

**Comment by rmpestano** [comment]
I actually don't know If we shouldn't create an OmniFaces extension separately or delivery an all in one JSF extension with MyFaces, PrimeFaces and OmniFaces (a quite Common JSF combo nowadays), WDYT?

**Comment by rmpestano** [comment]
Note that `PostConstruct` and `PreDestroy` events are not being triggered for OmniFaces ViewScope

**Comment by tandraschko** [comment]
You have to register scopes; see MyFacesProcessor#buildCdiScopes

I would not mix this with this extension here

**Comment by rmpestano** [comment]
> I would not mix this with this extension here

Alright, also don't think it is a good idea, I'll create another extension for OmniFaces.

**Pull request closed without merging**
